# Generated by Django 3.2 on 2024-11-24 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barberia',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('horario', models.JSONField(default=dict)),
                ('servicios', models.JSONField(default=list)),
                ('estado', models.CharField(default='cerrado', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DuenoBarberia',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('tipo', models.CharField(max_length=20)),
                ('estado_pago', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('tipo', models.CharField(max_length=20)),
                ('especialidades', models.JSONField(default=list)),
                ('horario', models.JSONField(default=dict)),
                ('curriculo', models.FileField(blank=True, null=True, upload_to='curriculos/')),
                ('barberia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarberMakerApp.barberia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tiempo_estimado', models.IntegerField()),
                ('barberia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortes', to='BarberMakerApp.barberia')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('servicio', models.CharField(max_length=100)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('detalles', models.JSONField(default=dict)),
                ('barberia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='BarberMakerApp.barberia')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='BarberMakerApp.cliente')),
                ('corte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BarberMakerApp.corte')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='BarberMakerApp.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='barberia',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barberias', to='BarberMakerApp.duenobarberia'),
        ),
        migrations.AddField(
            model_name='barberia',
            name='empleados',
            field=models.ManyToManyField(blank=True, related_name='barberias', to='BarberMakerApp.Empleado'),
        ),
    ]
