# Generated by Django 3.2 on 2024-11-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarberMakerApp', '0003_auto_20241124_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barberia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.IntegerField(choices=[(1, 'Abierto'), (0, 'Cerrado')])),
                ('direccion', models.CharField(max_length=255)),
                ('maps', models.TextField(blank=True, null=True)),
                ('horario1', models.TimeField()),
                ('horario2', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='CrearBarberia',
        ),
        migrations.AddField(
            model_name='barberia',
            name='cortes',
            field=models.ManyToManyField(to='BarberMakerApp.Corte'),
        ),
    ]
